### ISSUE TITLE
Merging snap objects

### ISSUE THREAD

**Issue by andrewhill157** [r3fang/SnapATAC#13]
I really love a lot of the ideas and functionality in SnapTools/SnapATAC, thanks for developing them both and congrats on the preprint!

Looking through the available functions, and am wondering if you think there might be a way to support merging of snap objects. I could obviously grab the binary matrices and merge them easily enough, but wondering if you think there might be a way to genuinely merge the objects so that all the other functionality in SnapTools could still be used as intended. The reason I ask is that we have several datasets that we have run in parallel to speed things up, but would be nice to be able to combine later for integrated analysis.

Thanks for the help!

**Comment by r3fang** [comment]
Hi,

Thank you for your kind message and thanks for try it! This is great question. 

The answer is yes. SnapTools does not support merge of multiple "snap" files but "SnapATAC" supports to merge multiple snap object in R. Here is one example how SnapATAC analyzes two samples together [here](https://github.com/r3fang/SnapATAC/blob/master/examples/10X_15k/10X_15k.md). You can merge multiple snap objects once they share cell-by-bin matrix of the same bin size. Last time i tried, I have no problem of merging up to 70 samples.

The reason that snaptools does not merge multiple snap files in to a single one is because I am trying to avoid creating a giant matrix that will slows down the read-in in SnapATAC. Also, as you mentioned, it would be nice to keep each sample separate so this can be run in parallel.

Does it answer your question?

Best
-Rongxin

**Comment by andrewhill157** [comment]
Thanks so much, I hadn't noticed that tutorial, very helpful! All makes
sense, will give it a shot and thanks again.

**Comment by r3fang** [comment]
No problem. Thank you for trying! Please don't hesitate to contact me if you have any question!

**Comment by r3fang** [comment]
You might have seen this, but just want to bring this up in case. There is a session in the main page called FAQs which has answered some questions regarding the compatibility with 10X data. https://github.com/r3fang/SnapATAC

**Comment by andrewhill157** [comment]
Awesome, thanks very much! Will let you know if I have any more questions and thanks again :)
