### ISSUE TITLE
About the filtering cells based on FIP ratio

### ISSUE THREAD

**Issue by seishin0125** [r3fang/SnapATAC#25]
In your criteria in filtering cells based on ratio, it seems that you calculated the ratio of sequencing reads belong to the "bins" overlapped with promoter region.
However, this ratio would be affected by the size of bins.
(If the binsize became larger, the chance of the bin overlapped with promoter would also become higher.)

Is there any good way to tune the threshold of FIP ratio based on the binsize?

> promoter.df = read.table("promoter.bed");
> promoter.gr = GRanges(promoter.df[,1], IRanges(promoter.df[,2], promoter.df[,3]));
> ov = findOverlaps(x.sp@feature, promoter.gr);
> idy = queryHits(ov);
> promoter_ratio = SnapATAC::rowSums(x.sp[,idy, mat="bmat"], mat="bmat") / SnapATAC::rowSums(x.sp, mat="bmat");
> plot(log(SnapATAC::rowSums(x.sp, mat="bmat") + 1,10), promoter_ratio, cex=0.5, col="grey", xlab="log(count)", ylab="FIP Ratio", ylim=c(0,1 ));
> idx = which(promoter_ratio > 0.2 & promoter_ratio < 0.8);
> x.sp = x.sp[idx,]

**Comment by r3fang** [comment]
Hi there!

You are totally right about it. Currently, I recommend to use 5kb and select cells with promoter ratio within 02-0.8. Please note this is a very subjective number based on my experience with multiple datasets generated from different platforms. Other bin sizes have not been tested

Best

**Comment by seishin0125** [comment]
Thank you so much for quick reply!

I have tried to analyse the scATAC data from your laboratory (Preissl et al., 2018; used the cells isolated from E11.5-P0 cortices) with SnapATAC, but about 1/3 of the cells were filtered due to the low FIP ratio.
Is it OK to shift the threshold for filtering cells by FIP ratio dependent on the samples and are there any tips in deciding the threshold for filtering cells (e.g. if the distribution of FIP ratio was bimodal, remove the cells included in "the lower peak") ?

In addition to that, I would like to ask you about the definition of promoter.bed in your laboratory.
( I think the definition of promoter would also affect the FIP ratio of the cell.)
I obtained "promoter.bed" file by
> wget http://renlab.sdsc.edu/r3fang/share/Fang_2019/MOs_snATAC/genes/promoter.bed

and noticed that the width of promoters vary from narrow to broad. 
How the promoter of each gene was determined?

Again, thank you so much for providing us a fantastic analytic tool for scATAC-seq. I'm really looking forward to diving into the field of the single-cell epigenomics using this tool.

[fragments_in_promoterratio_bingren.pdf]
(https://github.com/r3fang/SnapATAC/files/3171492/fragments_in_promoterratio_bingren.pdf)

**Comment by r3fang** [comment]
I have tried to analyse the scATAC data from your laboratory (Preissl et al., 2018; used the cells isolated from E11.5-P0 cortices) with SnapATAC, but about 1/3 of the cells were filtered due to the low FIP ratio.
Is it OK to shift the threshold for filtering cells by FIP ratio dependent on the samples and are there any tips in deciding the threshold for filtering cells (e.g. if the distribution of FIP ratio was bimodal, remove the cells included in "the lower peak") ?

**_the cutoff used for FIP is very subjective, totally based on my personal experience with all the datasets that i have processed. Preissl et al was performed against frozen sample, which may have lower quality,  I am not surprised to see 1/3 of barcodes are filtered. But how many cells do you end up with after filetering?_**

In addition to that, I would like to ask you about the definition of promoter.bed in your laboratory.
( I think the definition of promoter would also affect the FIP ratio of the cell.)
I obtained "promoter.bed" file by

**_the promoter.bed is a merged promoter list derived from genecode annotation (2k upstream). Overlapping promoters are merged, that's why the length is different._**  

Again, thank you so much for providing us a fantastic analytic tool for scATAC-seq. I'm really looking forward to diving into the field of the single-cell epigenomics using this tool.

**_Thank you fro such nice note! Please let me know if you have other question or anything that i can help._**

**Comment by seishin0125** [comment]
>The cutoff used for FIP is very subjective, totally based on my personal experience with all the datasets that i have processed. Preissl et al was performed against frozen sample, which may have lower quality, I am not surprised to see 1/3 of barcodes are filtered. But how many cells do you end up with after filtering?

I have totally missed that point! 67,652 cells were remained, and I think this number is enough to do further analysis. (The number of remained cells were 287013 → 88544 (remove UMI < 1000, followed the filtering threshold in Preissl et al., 2018) → 67652 (remove FIP <0.2 & FIP > 0.8).)

>The promoter.bed is a merged promoter list derived from genecode annotation (2k upstream). Overlapping promoters are merged, that's why the length is different.

"Overlapping" means that overlapping with other gene body or other promoter? But I'm still wondering why the length of each promoter is multiple of 200bases.

**Comment by r3fang** [comment]
"Overlapping" means that overlapping with other gene body or other promoter? But I'm still wondering why the length of each promoter is multiple of 200bases.

```
This is promoter list I got from someone else, because the FIP is counted using the cell-by-bin matrix, therefore, the promoter does not have to be exactly -2000 upstream of TSS. You can either download a precise promoter regions from UCSC genome browser or by other means. 
```

**Comment by seishin0125** [comment]
I see! Thank you so much!!
