### ISSUE TITLE
How to determine the parameter of significant PC/K in KNN graph construction

### ISSUE THREAD

**Issue by seishin0125** [r3fang/SnapATAC#32]
I am very afraid of asking this kind of basic question but, I'm wondering how to set reasonable parameters in runKNN() functions.

In "Mouse Secondary Motor Cortex 10k Nuclei" example, pca.dims=2:40 was set, but I couldn't get how to select "significant PCs" from the output of plotDimReductPW(). (The distribution of 2D plots after PC29 vs PC30 look quite similar for me.)
Are there any tips to determine "significant PCs" in runKNN() functions? 

In addition to this, are there any good ways of fine-tuning K for KNN in clustering?

**Comment by r3fang** [comment]
Hi there,

this is great question! There are two things here:

1) `pca.dims=2:40` as you can see I have discard the first PC because its large variance.
2) the reason that I choose 2:40 because I want to make it consistent with other dimensionality reduction technique to make a fair comparison except for LDA which automatically choose the optimal dimention/topic
3) if you set `weight.by.var=TRUE` 2:40 or 2:30 will not make too much difference because it is going to be the first few dims determine the overall structure. 
4) usually, I set pc.dims to 2:40 if `weight.by.var=TRUE` (recommand)
5) I carefully choose pc.dims if `weight.by.var=FALSE` and include the first dim as 1:30 for example. 

Let me know if this answers your question
Best

**Comment by r3fang** [comment]
again, this is a great question. I will add more detailed instructions in the tutorial

**Comment by seishin0125** [comment]
Thank you so much for answer! This instruction is really helpful for me to decide the condition for dimension reductions.

But I think that PC with large variance is also important to confer the original structure of the dataset. Are there any criterion for deciding whether to remove the PC (with large variance) or not?

> x.jda.sp = runKNN(
    obj=x.jda.sp,
    pca.dims=2:40,
    weight.by.sd=TRUE,
    k=15
    )

In addition to this, "k" is also set in runKNN() function. How is this "k=15" condition fixed in this code?

**Comment by r3fang** [comment]
Sent from my iPhone

> On May 14, 2019, at 10:47 PM, seishin0125 <notifications@github.com> wrote:
> 
> Thank you so much for answer! This instruction is really helpful for me to decide the condition for dimension reductions.
> 
> But I think that PC with large variance is also important to confer the original structure of the dataset. Are there any criterion for deciding whether to remove the PC (with large variance) or not?
> 

Removing the first dimension was first introduced by LSI to remove the dim that correlated with sequencing depth
> x.jda.sp = runKNN(
> obj=x.jda.sp,
> pca.dims=2:40,
> weight.by.sd=TRUE,
> k=15
> )
> 
> In addition to this, "k" is also set in runKNN() function. How is this "k=15" condition fixed in this code?
> 

15 or 30 is what people usually use for finding cluster using graph based clustering. You can try different number, it won’t change the result very much

**Comment by seishin0125** [comment]
> Removing the first dimension was first introduced by LSI to remove the dim that correlated with sequencing depth.

Does this mean that the contribution of sequencing depth is not fully removed in normalization in dimension reduction (e.g. "normOVE" in JDA)?

Now my question about the parameters in KNN graph construction was totally resolved!
Thank you so much for your kind assistance!
