### ISSUE TITLE
single-cell cell type labels - 10x Genomics 

### ISSUE THREAD

**Issue by znavidi** [r3fang/SnapATAC#43]
Hi,

I would like to know where should I find the cell type labels of a single cell dataset like this 10x Genomics link, which is required for evaluating SnapATAC outputs:
https://support.10xgenomics.com/single-cell-atac/datasets/1.0.1/atac_v1_hgmm_500

Thanks

**Comment by r3fang** [comment]
Hi there,

I think this is a question you should ask 10X.

**Comment by znavidi** [comment]
I would like to know what labeled real data you have used for the evaluation of your tool? and where are the labels?

**Comment by r3fang** [comment]
there is no real dataset that I used for evaluating the method that has "ground" truth. The annotation is only based on the marker genes enrichment according to prior knowledge. The only single cell ATAC-seq data that has "ground" truth truth is from "Schep Nature Methods" generated from sorted cell lines using fluigdium C1 protocal from different batches.

**Comment by znavidi** [comment]
Do you mean the one you used for this evaluation:
To further assess the performance of SnapATAC, it is used to analyze a series of published single cell chromatin accessibility datasets representing a variety of sample types, and the results are compared to the original analysis. When applied to a set of 1,452 human cells corresponding to 10 distinct cell types, SnapATAC successfully uncovered distinct cell populations with an accuracy of 0.95 (normalized mutual index) according to the cell labels, while the original method (chromVAR) failed to fully distinguish several blood cell subtypes (HL60, Blast, LMPP, LSC and Mono).
Because I think you need class labels (true cell types) for obtaining normalized mutual index. 

Also, I searched and found these datasets in chromVAR paper, but I don't know which one has ground truth labels and where can I find them. I really appreciate if you could help me with that if you have any link or other information.
Series GSE99172, GSE74310, GSE65360.

Best

**Comment by r3fang** [comment]
`Do you mean the one you used for this evaluation:
To further assess the performance of SnapATAC, it is used to analyze a series of published single cell chromatin accessibility datasets representing a variety of sample types, and the results are compared to the original analysis. When applied to a set of 1,452 human cells corresponding to 10 distinct cell types, SnapATAC successfully uncovered distinct cell populations with an accuracy of 0.95 (normalized mutual index) according to the cell labels, while the original method (chromVAR) failed to fully distinguish several blood cell subtypes (HL60, Blast, LMPP, LSC and Mono).
Because I think you need class labels (true cell types) for obtaining normalized mutual index.
`
Yes.

`
Also, I searched and found these datasets in chromVAR paper, but I don't know which one has ground truth labels and where can I find them. I really appreciate if you could help me with that if you have any link or other information.
Series GSE99172, GSE74310, GSE65360.
`
I simply used their cell-by-peak matrix from GSE99172
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE99172

**Comment by znavidi** [comment]
Thank you.
But I don't understand why you used the cell-by-peak matrix. You mentioned in the paper that you run snapATAC considering whole genome all valid bins (including off-peak bins), right? 

And also I would appreciate if you could help me know where could I find the labels of this dataset? I can't find it.

Best,

**Comment by r3fang** [comment]
It is only for this data that I used cell-by-peak matrix simply because this is the only matrix that is available etc. it’s a bit complicated to start from raw fast files for this data.

You can ask the author to provide the label.

**Comment by znavidi** [comment]
I got it. 
Thank you!
