### ISSUE TITLE
runJDA produces nothing?

### ISSUE THREAD

**Issue by cnk113** [r3fang/SnapATAC#54]
Hello,

I'm running to an issue where the runJDA w/ normalization looks like it runs perfectly fine, but when I check my object the Number of cells: 0 and Normalization is false. Any ideas on the issue?

Thanks

**Comment by r3fang** [comment]
Hi,

Maybe run it with separate steps instead of runJDA?

https://github.com/r3fang/SnapATAC/blob/206f28690c8f1d39e72598282c5dc62aa017c1e5/examples/10X_P50/README.md <https://github.com/r3fang/SnapATAC/blob/206f28690c8f1d39e72598282c5dc62aa017c1e5/examples/10X_P50/README.md>

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by cnk113** [comment]
Yeah that works thanks.
